-- Migration: create copilot_events table
-- Generated by agent

CREATE TABLE IF NOT EXISTS copilot_events (
  id varchar PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id varchar NOT NULL,
  event_type varchar(50) NOT NULL,
  suggestion_id varchar,
  payload jsonb,
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE IF EXISTS copilot_events
  ADD CONSTRAINT fk_copilot_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_copilot_events_user_id ON copilot_events(user_id);
CREATE INDEX IF NOT EXISTS idx_copilot_events_event_type ON copilot_events(event_type);
CREATE INDEX IF NOT EXISTS idx_copilot_events_created_at ON copilot_events(created_at);
